language: php
dist: focal
php:
- '8.1'
- '8.2'
env:
  global:
  - PACKAGE=wp-dev-tools
  - VERSION=v1.2.1
addons:
  apt:
    packages:
    - libonig5
install:
  # Vendor dependencies
  - composer install
  # PHIVE
  - wget -O phive.phar "https://phar.io/releases/phive.phar"
  - wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
  #- gpg --yes --keyserver hkps://keys.openpgp.org --recv-keys 0x9D8A98B29B2D5D79
  #- gpg --verify phive.phar.asc phive.phar
  #- rm phive.phar.asc
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/local/bin/phive
  - phive version
  # Box
  - yes | phive install humbug/box --force-accept-unsigned
  - sudo mv tools/box /usr/local/bin/box
  - box --version
script:
  # Run test suites
  - vendor/bin/phpunit --testsuite unit
  - vendor/bin/phpunit --testsuite integration
before_deploy:
  # Generate version number without leading 'v'
  - NUM_VERSION="${VERSION/#v/}"
  - NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$NUM_VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
  # Build package and binaries
  - composer install --no-dev --optimize-autoloader
  - sed -i -r "s/(VERSION.*)(@git_tag@)/\1$NUM_VERSION/" bin/createDetailsFile.php
  - box compile
  - rm -rf $PACKAGE || exit 0
  - mkdir $PACKAGE
  - cp -a ./bin $PACKAGE/
  - cp -a ./src $PACKAGE/
  - cp -a ./vendor $PACKAGE/
  - cp CHANGELOG.md $PACKAGE/
  - cp LICENSE $PACKAGE/
  - cp README.md $PACKAGE/
  - FILENAME=$PACKAGE-$VERSION
  - tar -czf $FILENAME.tar.gz $PACKAGE
  - zip -r $FILENAME.zip $PACKAGE
  # Save deployment values
  - export TRAVIS_TAG="$VERSION"
  - export GITHUB_NAME="$VERSION"
  - export GITHUB_RELEASE_NOTES="$NOTES"
deploy:
  provider: releases
  api_key:
    secure: gmbdlpI4Mgnpz5mBuUqyjRW+0wtsJk4H19mrlsthOoxWFAb1ypfseQSmup01Ezj2HBa9E1GkA3xvIE46bwK2JJy8y3k+ev131DVWzFsMUr6ye/5BPlviWW9N7UA+KcTlqExCUarYHlk3ZqTdaEZZ7mkByWsq3mbH57CB99hue0HYegyALfQ9AzbOr5Ffc3Vhgh/GCWfwDHqhr6hFsrapTUaFnCdtpRZjCAJ5nfB4gByukElB4DgMLXv7vvQQU3UO3hz1DsdG2T28BU8zMhDQq8BP3gemDCrGrV1hofMCAYuWvDN+NCK5VRGcfHwweq3t4p9ZEo5Tz1XhQMcqAjRsqClBnCJUYIMHYgTOWyr3aYBKKrr3nsj26h/Y5giVyiUX5p9bm87ahNlb53eyVENAy7NRO37hU15+hSfQ6Tav40Jr45ys0/e+oy04LM111VV6lDq5cr+1NRlUqMCZY6QWVtqB4dQYW6k7kXwr16u9KimPq0pB/AZ1+Sz2N+ryWyFugo6daSDaI8e+6CKNKVRFUVg7PtFC2Q5DqmLwaBHulYYCq65hSnqqZqNWf4JT8ze53AoPabw2QG/CRNdXU3+IpZzFCP/j4zEt2A+u1MmwxAsmY6A3DbU55z2AQ4Z1G5P5kcWtzBXI8aGk90oKdksKHyPYUAvxL3FQhMkrq9+cx4Q=
  file:
    - bin/createDetailsFile.phar
    - $FILENAME.tar.gz
    - $FILENAME.zip
  on:
    repo: questionmuppet/wp-dev-tools
  skip_cleanup: 'true'
