language: php
php:
- 7.4
install:
# Project dependencies
- composer install
# Phive
- wget -O phive.phar "https://phar.io/releases/phive.phar"
- wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
- gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
- gpg --verify phive.phar.asc phive.phar
- rm phive.phar.asc
- chmod +x phive.phar
- sudo mv phive.phar /usr/local/bin/phive
- phive version
# Box
- phive install humbug/box --force-accept-unsigned
- sudo mv tools/box /usr/local/bin/box
- box --version
script:
- composer update --no-dev
- box compile
deploy:
  provider: releases
  skip_cleanup: true
  on:
    tags: true