language: php
php:
  - 7.4
env:
  global:
    VERSION=1.1-dev-12
branches:
  only:
    - master
    - develop
install:
  # Vendor dependencies
  - composer install
  # PHIVE
  - wget -O phive.phar "https://phar.io/releases/phive.phar"
  - wget -O phive.phar.asc "https://phar.io/releases/phive.phar.asc"
  - gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9D8A98B29B2D5D79
  - gpg --verify phive.phar.asc phive.phar
  - rm phive.phar.asc
  - chmod +x phive.phar
  - sudo mv phive.phar /usr/local/bin/phive
  - phive version
  # Box
  - phive install humbug/box --force-accept-unsigned
  - sudo mv tools/box /usr/local/bin/box
  - box --version
script:
  # Run test suites
  - phpunit --testsuite unit
  - phpunit --testsuite integration
before_deploy:
  # Build package and binaries
  - composer update --no-dev
  - sed -i -r "s/(VERSION.*)(@git_tag@)/\1$VERSION/" bin/createDetailsFile.php
  - box compile
  # Save deployment values
  - COMMIT=`git log --format=%h -1`
  - export GITHUB_RELEASE_NOTES="`cat CHANGELOG.md | sed -r '0,/^## \['$VERSION'\]/d' | sed -r '/^\s*$/,$d'`"
  - export GITHUB_NAME="$VERSION - Dev release $COMMIT"
  - export TRAVIS_TAG="$VERSION"
  # Ensure unique tag for this release
  - [[ ! -z `git tag | grep $VERSION` ]] && TRAVIS_TAG="$TRAVIS_TAG-$COMMIT"
deploy:
  provider: releases
  edge: true
  api_key:
    secure: NtFayUcRKCifDS74I2PGvhQXaCI0dqUYJYowzr7PczWfaKtdfpeOG7rLuC2NMAWqaK/SjEFcSwaCTXp+gbkNJLRir0xzv7tlkVceEf3q597SjGkaU681jsrYlicmaV3rf6udVQ5T6iXOVj8Xh6VW151p0DkDr/DEceCPSlO2efzaaiQOHI+RzwPx9PgvP4CQpQ5tj4hWNmpMyvZTR519HjanicYYjymnFY4pOI2GrQtjk1D/fUZ6PfOxQalwneLIWxANoEDj4pahfEhZtKZl6BiMC35uNE8ZnGA7ukVJMWPpaduVjACrR/VY08o0LXs+hj0LevZ1GsL4wUAL/9gKgeeRA47Rr3sWyGHeRkDB7sr5Jvz0kxlJChsWCHin3obVtUXMMu8f4CBoHRg+MJRiXIktnUURZx2VGHXxuKsYuSvO64x+r09wql7QMi/SchVKpNZaPd0tZnNzf4voKkWikYPF13uUDOMGSOyv+R1+lrCBx+/pWurPOZVliFh/2ikpjE01Et/YWuvK5I+VmsR/Nm1ussDzUf+tD6CWJUzWRLjV0yylE9frsBH+pLyw+7Arx9S7ZUgnBDWj2+QNMQBiDbIvugU5WrAM8u1C0lrltPC5m9Dy9ItYS286nikMD+FiEVF/S2Y2o6+Q2132uYEvpUI+Jv0trn4Sw9P1PSDpOn0=
  file: bin/createDetailsFile.phar
  on:
    tags: true
